"""
Pure physics functions – no mutable state, no side-effects.

Coordinate system
-----------------
* +x  → right (downrange)
* +y  → up (altitude)
* θ   → angle of the rocket body axis measured CCW from +x
         (θ = π/2  →  rocket points straight up)
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

from config import EnvironmentConfig, StageConfig
from utils import Vec2, direction_from_angle, magnitude, normalise, vec2


# ---------------------------------------------------------------------------
# Atmosphere helpers
# ---------------------------------------------------------------------------

def air_density(altitude: float, env: EnvironmentConfig) -> float:
    """Exponential atmosphere model.  Returns ρ in kg/m³."""
    if altitude < 0:
        altitude = 0.0
    return env.rho0 * math.exp(-altitude / env.scale_height)


def gravity_acceleration(altitude: float, env: EnvironmentConfig) -> float:
    """Gravitational acceleration at a given altitude (m/s²)."""
    if not env.use_altitude_gravity:
        return env.g0
    r = env.earth_radius + max(altitude, 0.0)
    return env.g0 * (env.earth_radius / r) ** 2


# ---------------------------------------------------------------------------
# Force computations
# ---------------------------------------------------------------------------

def gravity_force(total_mass: float, altitude: float, env: EnvironmentConfig) -> Vec2:
    g = gravity_acceleration(altitude, env)
    return vec2(0.0, -total_mass * g)


def thrust_force(
    throttle: float,
    rocket_angle: float,
    gimbal_angle: float,
    cfg: StageConfig,
    has_fuel: bool,
) -> Vec2:
    """
    Thrust along the rocket body axis offset by gimbal angle.

    *rocket_angle* is θ of the body; *gimbal_angle* offsets the nozzle
    relative to the body (positive = CCW).
    """
    if not has_fuel or throttle <= 0:
        return vec2()
    effective_angle = rocket_angle + gimbal_angle
    return direction_from_angle(effective_angle) * (throttle * cfg.max_thrust)


def drag_force(
    velocity: Vec2,
    altitude: float,
    rocket_angle: float,
    cfg: StageConfig,
    env: EnvironmentConfig,
) -> Vec2:
    """Aerodynamic drag decomposed into axial and lateral components."""
    speed = magnitude(velocity)
    if speed < 1e-6:
        return vec2()

    rho = air_density(altitude, env)

    # Body-frame decomposition
    body_axis = direction_from_angle(rocket_angle)
    v_axial = float(np.dot(velocity, body_axis))
    v_lateral_vec = velocity - v_axial * body_axis
    v_lateral = magnitude(v_lateral_vec)

    # Axial drag (along body)
    f_axial = 0.5 * rho * v_axial * abs(v_axial) * cfg.cd_axial * cfg.reference_area
    drag = -f_axial * body_axis

    # Lateral drag (perpendicular to body)
    if v_lateral > 1e-6:
        lateral_dir = v_lateral_vec / v_lateral
        side_area = cfg.length * cfg.diameter  # rough projected side area
        f_lateral = 0.5 * rho * v_lateral * abs(v_lateral) * cfg.cd_lateral * side_area
        drag = drag - f_lateral * lateral_dir

    return drag


def aerodynamic_torque(
    velocity: Vec2,
    altitude: float,
    rocket_angle: float,
    cfg: StageConfig,
    env: EnvironmentConfig,
) -> float:
    """
    Restoring + damping torque from aerodynamic forces.

    Uses the *reference area* (cross-section) and a realistic CP–CG offset
    to compute the pitching moment.  Also adds aerodynamic damping
    proportional to angular velocity (implicit through the alpha derivative).

    Returns torque in N·m (positive = CCW).
    """
    speed = magnitude(velocity)
    if speed < 1e-6:
        return 0.0

    rho = air_density(altitude, env)
    q = 0.5 * rho * speed ** 2

    # Angle of attack: angle between velocity vector and body axis
    vel_angle = math.atan2(velocity[1], velocity[0])
    alpha = rocket_angle - vel_angle
    alpha = (alpha + math.pi) % (2 * math.pi) - math.pi

    # Restoring moment: reference area × CP–CG lever.
    # CP–CG offset ≈ 0.5 calibres — moderate fin-stabilised rocket.
    cp_offset = 0.5 * cfg.diameter
    cn_alpha = 2.0  # normal-force coefficient slope (dimensionless)
    restoring = -q * cn_alpha * cfg.reference_area * cp_offset * math.sin(alpha)

    return restoring


def thrust_torque(
    throttle: float,
    gimbal_angle: float,
    cfg: StageConfig,
    has_fuel: bool,
) -> float:
    """Torque generated by an off-axis thrust vector (gimbal)."""
    if not has_fuel or throttle <= 0:
        return 0.0
    lever = cfg.length / 2  # nozzle at the tail
    force_magnitude = throttle * cfg.max_thrust
    return -force_magnitude * math.sin(gimbal_angle) * lever


# ---------------------------------------------------------------------------
# Derived quantities
# ---------------------------------------------------------------------------

def dynamic_pressure(velocity: Vec2, altitude: float, env: EnvironmentConfig) -> float:
    speed = magnitude(velocity)
    rho = air_density(altitude, env)
    return 0.5 * rho * speed ** 2


def moment_of_inertia(total_mass: float, cfg: StageConfig) -> float:
    return cfg.moment_of_inertia_factor * total_mass * cfg.length ** 2


# ---------------------------------------------------------------------------
# State derivative (used by integrators)
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class RocketState:
    """Minimal state vector used by the integrator."""
    x: float = 0.0
    y: float = 0.0
    vx: float = 0.0
    vy: float = 0.0
    theta: float = math.pi / 2   # pointing up
    omega: float = 0.0
    fuel: float = 0.0

    def to_array(self) -> np.ndarray:
        return np.array([self.x, self.y, self.vx, self.vy, self.theta, self.omega, self.fuel])

    @classmethod
    def from_array(cls, a: np.ndarray) -> "RocketState":
        return cls(x=a[0], y=a[1], vx=a[2], vy=a[3], theta=a[4], omega=a[5], fuel=a[6])


def state_derivative(
    state: RocketState,
    throttle: float,
    gimbal_angle: float,
    rcfg: StageConfig,
    ecfg: EnvironmentConfig,
) -> np.ndarray:
    """
    Compute dy/dt for the 7-element state vector.

    Returns an array of the same shape: [dx, dy, dvx, dvy, dtheta, domega, dfuel].
    """
    has_fuel = state.fuel > 0
    total_mass = rcfg.dry_mass + max(state.fuel, 0.0)
    altitude = max(state.y, 0.0)

    velocity = vec2(state.vx, state.vy)

    # --- Forces ---
    f_gravity = gravity_force(total_mass, altitude, ecfg)
    f_thrust = thrust_force(throttle, state.theta, gimbal_angle, rcfg, has_fuel)
    f_drag = drag_force(velocity, altitude, state.theta, rcfg, ecfg)
    f_total = f_gravity + f_thrust + f_drag

    ax = f_total[0] / total_mass
    ay = f_total[1] / total_mass

    # --- Torques ---
    tau_thrust = thrust_torque(throttle, gimbal_angle, rcfg, has_fuel)
    tau_aero = aerodynamic_torque(velocity, altitude, state.theta, rcfg, ecfg)
    I = moment_of_inertia(total_mass, rcfg)
    alpha = (tau_thrust + tau_aero) / I if I > 0 else 0.0

    # --- Fuel consumption ---
    if has_fuel and throttle > 0:
        dm = -throttle * rcfg.burn_rate
    else:
        dm = 0.0

    return np.array([state.vx, state.vy, ax, ay, state.omega, alpha, dm])
